name: A2
packageName: Assignment-2-constant-propagation-worklist-solver.zip
exclude:
  - pascal.taie.analysis.graph.callgraph.*
  - pascal.taie.analysis.graph.icfg.*
  - pascal.taie.analysis.pta.*
  - pascal.taie.analysis.dataflow.analysis.*
  - pascal.taie.analysis.dataflow.fact.*
  - pascal.taie.analysis.dataflow.solver.*
  - pascal.taie.analysis.dataflow.inter.*
sourceFiles:
  - pascal.taie.ir.IR
  - pascal.taie.ir.stmt.Stmt
  - pascal.taie.ir.stmt.DefinitionStmt
  - pascal.taie.ir.exp.Exp
  - pascal.taie.ir.exp.Var
  - pascal.taie.ir.exp.IntLiteral
  - pascal.taie.ir.exp.BinaryExp
  - pascal.taie.ir.exp.ArithmeticExp
  - pascal.taie.ir.exp.ConditionExp
  - pascal.taie.ir.exp.BitwiseExp
  - pascal.taie.ir.exp.ShiftExp
  - pascal.taie.analysis.graph.cfg.CFG
  - pascal.taie.util.graph.Graph
  - pascal.taie.analysis.dataflow.analysis.DataflowAnalysis
  - pascal.taie.analysis.dataflow.analysis.AbstractDataflowAnalysis
  - pascal.taie.analysis.dataflow.fact.DataflowResult
  - pascal.taie.analysis.dataflow.fact.NodeResult
  - pascal.taie.analysis.dataflow.fact.MapFact
  - pascal.taie.analysis.dataflow.analysis.constprop.CPFact
  - pascal.taie.analysis.dataflow.analysis.constprop.Value
overwrittenFiles:
  - pascal.taie.analysis.dataflow.analysis.constprop.ConstantPropagation
  - pascal.taie.analysis.dataflow.solver.Solver
  - pascal.taie.analysis.dataflow.solver.WorkListSolver
  # complete
  - pascal.taie.analysis.dataflow.analysis.ResultProcessor
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder
  - pascal.taie.Assignment
testClasses:
  - pascal.taie.analysis.Tests
  - pascal.taie.analysis.dataflow.analysis.constprop.CPTest
testResources:
  - dataflow/constprop/Assign.java
  - dataflow/constprop/SimpleConstant.java
  - dataflow/constprop/SimpleBinary.java
  - dataflow/constprop/SimpleBranch.java
  - dataflow/constprop/SimpleChar.java
  - dataflow/constprop/BranchConstant.java
  - dataflow/constprop/Interprocedural.java
