name: A6
analyses: [ cspta ]
packageName: Assignment-6-context-sensitive-pointer-analysis.zip
exclude:
  - pascal.taie.analysis.dataflow.*
  - pascal.taie.analysis.exception.*
  - pascal.taie.analysis.graph.callgraph.CHA*
  - pascal.taie.analysis.graph.cfg.*
  - pascal.taie.analysis.graph.icfg.*
  - pascal.taie.analysis.pta.ci.*
  - pascal.taie.analysis.pta.cs.*
  - pascal.taie.analysis.pta.core.cs.context.*
  - pascal.taie.analysis.pta.core.cs.selector.*
  - pascal.taie.analysis.pta.core.solver.*
  - pascal.taie.analysis.pta.plugin.*
  - pascal.taie.analysis.pta.PointerAnalysis
  - pascal.taie.analysis.Tests
sourceFiles:
  - pascal.taie.analysis.graph.callgraph.AbstractCallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder
  - pascal.taie.analysis.graph.callgraph.CallKind
  - pascal.taie.analysis.graph.callgraph.Edge
  - pascal.taie.analysis.pta.core.cs.CSCallGraph
  - pascal.taie.analysis.pta.core.cs.context.Context
  - pascal.taie.analysis.pta.core.cs.context.ListContext
  - pascal.taie.analysis.pta.core.cs.element.ArrayIndex
  - pascal.taie.analysis.pta.core.cs.element.CSCallSite
  - pascal.taie.analysis.pta.core.cs.element.CSElement
  - pascal.taie.analysis.pta.core.cs.element.CSManager
  - pascal.taie.analysis.pta.core.cs.element.CSMethod
  - pascal.taie.analysis.pta.core.cs.element.CSObj
  - pascal.taie.analysis.pta.core.cs.element.CSVar
  - pascal.taie.analysis.pta.core.cs.element.InstanceField
  - pascal.taie.analysis.pta.core.cs.element.Pointer
  - pascal.taie.analysis.pta.core.cs.element.StaticField
  - pascal.taie.analysis.pta.core.cs.selector.CISelector
  - pascal.taie.analysis.pta.core.cs.selector.ContextSelector
  - pascal.taie.analysis.pta.core.heap.HeapModel
  - pascal.taie.analysis.pta.core.heap.Obj
  - pascal.taie.analysis.pta.cs.CSPTA
  - pascal.taie.analysis.pta.cs.PointerFlowGraph
  - pascal.taie.analysis.pta.cs.WorkList
  - pascal.taie.analysis.pta.plugin.ResultProcessor
  - pascal.taie.analysis.pta.pts.PointsToSet
  - pascal.taie.analysis.pta.pts.PointsToSetFactory
  - pascal.taie.ir.exp.InvokeExp
  - pascal.taie.ir.exp.Var
  - pascal.taie.ir.IR
  - pascal.taie.ir.stmt.ArrayStmt
  - pascal.taie.ir.stmt.AssignStmt
  - pascal.taie.ir.stmt.Copy
  - pascal.taie.ir.stmt.DefinitionStmt
  - pascal.taie.ir.stmt.FieldStmt
  - pascal.taie.ir.stmt.Invoke
  - pascal.taie.ir.stmt.LoadArray
  - pascal.taie.ir.stmt.LoadField
  - pascal.taie.ir.stmt.New
  - pascal.taie.ir.stmt.Stmt
  - pascal.taie.ir.stmt.StmtVisitor
  - pascal.taie.ir.stmt.StoreArray
  - pascal.taie.ir.stmt.StoreField
  - pascal.taie.language.classes.JField
  - pascal.taie.language.classes.JMethod
overwrittenFiles:
  - pascal.taie.analysis.pta.cs.Solver
  - pascal.taie.analysis.pta.core.cs.selector._1CallSelector
  - pascal.taie.analysis.pta.core.cs.selector._1ObjSelector
  - pascal.taie.analysis.pta.core.cs.selector._1TypeSelector
  - pascal.taie.analysis.pta.core.cs.selector._2CallSelector
  - pascal.taie.analysis.pta.core.cs.selector._2ObjSelector
  - pascal.taie.analysis.pta.core.cs.selector._2TypeSelector
  # complete
  - pascal.taie.Assignment
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder # remove CHA dependencies
  - pascal.taie.analysis.pta.core.cs.element.Pointer # remove PFGEdge dependency
  - pascal.taie.analysis.pta.core.cs.element.AbstractPointer
  - pascal.taie.analysis.pta.plugin.ResultProcessor # remove Plugin and Solver dependencies
  - pascal.taie.analysis.Tests # remove CFG and DFA dependencies
testClasses:
  - pascal.taie.analysis.pta.CSPTATest
testResources:
  - pta/cspta/New.java
  - pta/cspta/Assign.java
  - pta/cspta/StoreLoad.java
  - pta/cspta/InstanceField.java
  - pta/cspta/Call.java
  - pta/cspta/Array.java
  - pta/cspta/StaticField.java
  - pta/cspta/OneCall.java
  - pta/cspta/OneObject.java
  - pta/cspta/OneType.java
  - pta/cspta/TwoCall.java
  - pta/cspta/TwoObject.java
  - pta/cspta/TwoType.java
