name: A5
analyses: [ cipta ]
packageName: Assignment-5-context-insensitive-pointer-analysis.zip
exclude:
  - pascal.taie.analysis.dataflow.*
  - pascal.taie.analysis.exception.*
  - pascal.taie.analysis.graph.cfg.*
  - pascal.taie.analysis.graph.icfg.*
  - pascal.taie.analysis.pta.PointerAnalysis
  - pascal.taie.analysis.pta.ci.*
  - pascal.taie.analysis.pta.cs.*
  - pascal.taie.analysis.pta.core.cs.*
  - pascal.taie.analysis.pta.core.solver.*
  - pascal.taie.analysis.pta.plugin.*
  - pascal.taie.analysis.pta.pts.*
  - pascal.taie.analysis.Tests
sourceFiles:
  - pascal.taie.language.classes.JMethod
  - pascal.taie.language.classes.JField
  - pascal.taie.ir.IR
  - pascal.taie.ir.exp.InvokeExp
  - pascal.taie.ir.stmt.Stmt
  - pascal.taie.ir.stmt.DefinitionStmt
  - pascal.taie.ir.stmt.Invoke
  - pascal.taie.ir.stmt.ArrayStmt
  - pascal.taie.ir.stmt.AssignStmt
  - pascal.taie.ir.stmt.Copy
  - pascal.taie.ir.stmt.FieldStmt
  - pascal.taie.ir.stmt.LoadArray
  - pascal.taie.ir.stmt.LoadField
  - pascal.taie.ir.stmt.New
  - pascal.taie.ir.stmt.StmtVisitor
  - pascal.taie.ir.stmt.StoreArray
  - pascal.taie.ir.stmt.StoreField
  - pascal.taie.ir.exp.Var
  - pascal.taie.analysis.graph.callgraph.AbstractCallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder
  - pascal.taie.analysis.graph.callgraph.CallKind
  - pascal.taie.analysis.graph.callgraph.DefaultCallGraph
  - pascal.taie.analysis.graph.callgraph.Edge
  - pascal.taie.analysis.pta.ci.ArrayIndex
  - pascal.taie.analysis.pta.ci.CIPTA
  - pascal.taie.analysis.pta.ci.PointsToSet
  - pascal.taie.analysis.pta.ci.PointerFlowGraph
  - pascal.taie.analysis.pta.ci.InstanceField
  - pascal.taie.analysis.pta.ci.CIPTAResult
  - pascal.taie.analysis.pta.ci.WorkList
  - pascal.taie.analysis.pta.ci.ResultProcessor
  - pascal.taie.analysis.pta.ci.Pointer
  - pascal.taie.analysis.pta.ci.Solver
  - pascal.taie.analysis.pta.ci.VarPtr
  - pascal.taie.analysis.pta.ci.StaticField
  - pascal.taie.analysis.pta.core.heap.HeapModel
  - pascal.taie.analysis.pta.core.heap.Obj
overwrittenFiles:
  - pascal.taie.analysis.pta.ci.Solver
  # complete
  - pascal.taie.Assignment
  - pascal.taie.analysis.pta.PointerAnalysisResult # remove CS-related classes
  - pascal.taie.analysis.pta.ci.CIPTAResult
  - pascal.taie.analysis.Tests # remove CFG and DFA dependencies
testClasses:
  - pascal.taie.analysis.pta.CIPTATest
testResources:
  - pta/cipta/Array.java
  - pta/cipta/Assign.java
  - pta/cipta/Assign2.java
  - pta/cipta/Call.java
  - pta/cipta/Example.java
  - pta/cipta/InstanceField.java
  - pta/cipta/StaticCall.java
  - pta/cipta/StaticField.java
  - pta/cipta/StoreLoad.java
  - pta/cipta/MergeParam.java
