name: A1
packageName: Assignment-1-live-variable-iterative-solver.zip
exclude:
  - pascal.taie.analysis.graph.callgraph.*
  - pascal.taie.analysis.graph.icfg.*
  - pascal.taie.analysis.pta.*
  - pascal.taie.analysis.dataflow.analysis.*
  - pascal.taie.analysis.dataflow.fact.*
  - pascal.taie.analysis.dataflow.solver.*
  - pascal.taie.analysis.dataflow.inter.*
sourceFiles:
  - pascal.taie.ir.stmt.Stmt
  - pascal.taie.ir.exp.Exp
  - pascal.taie.ir.exp.Var
  - pascal.taie.analysis.graph.cfg.CFG
  - pascal.taie.util.graph.Graph
  - pascal.taie.analysis.dataflow.analysis.DataflowAnalysis
  - pascal.taie.analysis.dataflow.analysis.AbstractDataflowAnalysis
  - pascal.taie.analysis.dataflow.fact.DataflowResult
  - pascal.taie.analysis.dataflow.fact.NodeResult
  - pascal.taie.analysis.dataflow.fact.SetFact
overwrittenFiles:
  - pascal.taie.analysis.dataflow.analysis.LiveVariableAnalysis
  - pascal.taie.analysis.dataflow.solver.Solver
  - pascal.taie.analysis.dataflow.solver.IterativeSolver
  # complete
  - pascal.taie.analysis.dataflow.analysis.ResultProcessor
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder
  - pascal.taie.Assignment
testClasses:
  - pascal.taie.analysis.Tests
  - pascal.taie.analysis.dataflow.analysis.LiveVarTest
testResources:
  - dataflow/livevar/Assign.java
  - dataflow/livevar/Branch.java
  - dataflow/livevar/BranchLoop.java
  - dataflow/livevar/Array.java
  - dataflow/livevar/Fibonacci.java
  - dataflow/livevar/Reference.java
