name: A7
analyses: [ inter-constprop ]
packageName: Assignment-7-alias-aware-interprocedural-constant-propagation.zip
exclude:
  - pascal.taie.analysis.dataflow.analysis.*
  - pascal.taie.analysis.dataflow.fact.*
  - pascal.taie.analysis.dataflow.solver.*
  - pascal.taie.analysis.dataflow.inter.*
  - pascal.taie.analysis.pta.ci.*
  - pascal.taie.analysis.pta.cs.*
  - pascal.taie.analysis.pta.core.cs.context.*
  - pascal.taie.analysis.pta.core.cs.selector.*
  - pascal.taie.analysis.pta.core.solver.*
  - pascal.taie.analysis.pta.plugin.*
  - pascal.taie.analysis.pta.PointerAnalysis
sourceFiles:
  - pascal.taie.analysis.StmtResult
  - pascal.taie.analysis.dataflow.analysis.AbstractDataflowAnalysis
  - pascal.taie.analysis.dataflow.analysis.constprop.CPFact
  - pascal.taie.analysis.dataflow.analysis.constprop.Value
  - pascal.taie.analysis.dataflow.analysis.DataflowAnalysis
  - pascal.taie.analysis.dataflow.fact.DataflowResult
  - pascal.taie.analysis.dataflow.fact.MapFact
  - pascal.taie.analysis.dataflow.fact.NodeResult
  - pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis
  - pascal.taie.analysis.dataflow.inter.InterDataflowAnalysis
  - pascal.taie.analysis.graph.callgraph.AbstractCallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder
  - pascal.taie.analysis.graph.callgraph.CallKind
  - pascal.taie.analysis.graph.callgraph.CGBuilder
  - pascal.taie.analysis.graph.callgraph.DefaultCallGraph
  - pascal.taie.analysis.graph.callgraph.Edge
  - pascal.taie.analysis.graph.cfg.CFG
  - pascal.taie.analysis.graph.icfg.CallEdge
  - pascal.taie.analysis.graph.icfg.CallToReturnEdge
  - pascal.taie.analysis.graph.icfg.ICFG
  - pascal.taie.analysis.graph.icfg.ICFGEdge
  - pascal.taie.analysis.graph.icfg.NormalEdge
  - pascal.taie.analysis.graph.icfg.ReturnEdge
  - pascal.taie.analysis.pta.core.cs.context.Context
  - pascal.taie.analysis.pta.core.cs.context.ListContext
  - pascal.taie.analysis.pta.core.cs.CSCallGraph
  - pascal.taie.analysis.pta.core.cs.element.ArrayIndex
  - pascal.taie.analysis.pta.core.cs.element.CSCallSite
  - pascal.taie.analysis.pta.core.cs.element.CSElement
  - pascal.taie.analysis.pta.core.cs.element.CSManager
  - pascal.taie.analysis.pta.core.cs.element.CSMethod
  - pascal.taie.analysis.pta.core.cs.element.CSObj
  - pascal.taie.analysis.pta.core.cs.element.CSVar
  - pascal.taie.analysis.pta.core.cs.element.InstanceField
  - pascal.taie.analysis.pta.core.cs.element.Pointer
  - pascal.taie.analysis.pta.core.cs.element.StaticField
  - pascal.taie.analysis.pta.core.cs.selector.CISelector
  - pascal.taie.analysis.pta.core.cs.selector.ContextSelector
  - pascal.taie.analysis.pta.core.heap.HeapModel
  - pascal.taie.analysis.pta.core.heap.Obj
  - pascal.taie.analysis.pta.cs.CSPTA
  - pascal.taie.analysis.pta.cs.PointerFlowGraph
  - pascal.taie.analysis.pta.cs.WorkList
  - pascal.taie.analysis.pta.plugin.ResultProcessor
  - pascal.taie.analysis.pta.PointerAnalysisResult
  - pascal.taie.analysis.pta.pts.PointsToSet
  - pascal.taie.analysis.pta.pts.PointsToSetFactory
  - pascal.taie.ir.exp.ArithmeticExp
  - pascal.taie.ir.exp.ArrayAccess
  - pascal.taie.ir.exp.BinaryExp
  - pascal.taie.ir.exp.BitwiseExp
  - pascal.taie.ir.exp.ConditionExp
  - pascal.taie.ir.exp.Exp
  - pascal.taie.ir.exp.IntLiteral
  - pascal.taie.ir.exp.InvokeExp
  - pascal.taie.ir.exp.ShiftExp
  - pascal.taie.ir.exp.Var
  - pascal.taie.ir.IR
  - pascal.taie.ir.stmt.ArrayStmt
  - pascal.taie.ir.stmt.AssignStmt
  - pascal.taie.ir.stmt.Copy
  - pascal.taie.ir.stmt.DefinitionStmt
  - pascal.taie.ir.stmt.FieldStmt
  - pascal.taie.ir.stmt.Invoke
  - pascal.taie.ir.stmt.LoadArray
  - pascal.taie.ir.stmt.LoadField
  - pascal.taie.ir.stmt.New
  - pascal.taie.ir.stmt.Stmt
  - pascal.taie.ir.stmt.StmtVisitor
  - pascal.taie.ir.stmt.StoreArray
  - pascal.taie.ir.stmt.StoreField
  - pascal.taie.language.classes.JField
  - pascal.taie.language.classes.JMethod
overwrittenFiles:
  - pascal.taie.analysis.dataflow.analysis.constprop.ConstantPropagation
  - pascal.taie.analysis.dataflow.solver.Solver
  - pascal.taie.analysis.dataflow.solver.WorkListSolver
  - pascal.taie.analysis.dataflow.inter.InterConstantPropagation
  - pascal.taie.analysis.dataflow.inter.InterSolver
  - pascal.taie.analysis.pta.cs.Solver
  - pascal.taie.analysis.pta.core.cs.selector._1CallSelector
  - pascal.taie.analysis.pta.core.cs.selector._1ObjSelector
  - pascal.taie.analysis.pta.core.cs.selector._1TypeSelector
  - pascal.taie.analysis.pta.core.cs.selector._2CallSelector
  - pascal.taie.analysis.pta.core.cs.selector._2ObjSelector
  - pascal.taie.analysis.pta.core.cs.selector._2TypeSelector
  # complete
  - pascal.taie.Assignment
  - pascal.taie.analysis.ResultProcessor # handle empty call graph
  - pascal.taie.analysis.pta.core.cs.element.Pointer # remove PFGEdge dependency
  - pascal.taie.analysis.pta.core.cs.element.AbstractPointer
  - pascal.taie.analysis.pta.plugin.ResultProcessor # remove Plugin and Solver dependencies
testClasses:
  - pascal.taie.analysis.Tests
  - pascal.taie.analysis.dataflow.analysis.constprop.InterCPAliasTest
testResources:
  - dataflow/constprop/alias/Array.java
  - dataflow/constprop/alias/ArrayInter2.java
  - dataflow/constprop/alias/ArrayLoops.java
  - dataflow/constprop/alias/InstanceField.java
  - dataflow/constprop/alias/MultiStores.java
  - dataflow/constprop/alias/Interprocedural2.java
  - dataflow/constprop/alias/ObjSens.java
  - dataflow/constprop/alias/StaticField.java
  - dataflow/constprop/alias/StaticFieldMultiStores.java
