name: A4
packageName: Assignment-4-cha-interprocedural-constant-propagation.zip
exclude:
  - pascal.taie.analysis.graph.callgraph.*
  - pascal.taie.analysis.pta.*
  - pascal.taie.analysis.dataflow.analysis.*
  - pascal.taie.analysis.dataflow.fact.*
  - pascal.taie.analysis.dataflow.solver.*
  - pascal.taie.analysis.dataflow.inter.*
sourceFiles:
  - pascal.taie.language.classes.JClass
  - pascal.taie.language.classes.JMethod
  - pascal.taie.language.classes.Subsignature
  - pascal.taie.ir.IR
  - pascal.taie.ir.stmt.Stmt
  - pascal.taie.ir.stmt.DefinitionStmt
  - pascal.taie.ir.stmt.Invoke
  - pascal.taie.ir.exp.Exp
  - pascal.taie.ir.exp.Var
  - pascal.taie.ir.exp.IntLiteral
  - pascal.taie.ir.exp.BinaryExp
  - pascal.taie.ir.exp.ArithmeticExp
  - pascal.taie.ir.exp.ConditionExp
  - pascal.taie.ir.exp.BitwiseExp
  - pascal.taie.ir.exp.ShiftExp
  - pascal.taie.ir.exp.InvokeExp
  - pascal.taie.ir.proginfo.MethodRef
  - pascal.taie.analysis.graph.cfg.CFG
  - pascal.taie.analysis.graph.icfg.ICFG
  - pascal.taie.analysis.graph.icfg.CallEdge
  - pascal.taie.analysis.graph.icfg.CallToReturnEdge
  - pascal.taie.analysis.graph.icfg.ICFGEdge
  - pascal.taie.analysis.graph.icfg.NormalEdge
  - pascal.taie.analysis.graph.icfg.ReturnEdge
  - pascal.taie.util.graph.Graph
  - pascal.taie.analysis.dataflow.analysis.DataflowAnalysis
  - pascal.taie.analysis.dataflow.analysis.AbstractDataflowAnalysis
  - pascal.taie.analysis.dataflow.fact.DataflowResult
  - pascal.taie.analysis.dataflow.fact.NodeResult
  - pascal.taie.analysis.dataflow.fact.MapFact
  - pascal.taie.analysis.dataflow.analysis.constprop.CPFact
  - pascal.taie.analysis.dataflow.analysis.constprop.Value
  - pascal.taie.analysis.dataflow.inter.AbstractInterDataflowAnalysis
  - pascal.taie.analysis.dataflow.inter.InterDataflowAnalysis
  - pascal.taie.analysis.graph.callgraph.AbstractCallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraph
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder
  - pascal.taie.analysis.graph.callgraph.CallKind
  - pascal.taie.analysis.graph.callgraph.CGBuilder
  - pascal.taie.analysis.graph.callgraph.DefaultCallGraph
  - pascal.taie.analysis.graph.callgraph.Edge
overwrittenFiles:
  - pascal.taie.analysis.dataflow.analysis.constprop.ConstantPropagation
  - pascal.taie.analysis.dataflow.inter.InterConstantPropagation
  - pascal.taie.analysis.dataflow.inter.InterSolver
  - pascal.taie.analysis.graph.callgraph.CHABuilder
  - pascal.taie.analysis.dataflow.solver.Solver
  - pascal.taie.analysis.dataflow.solver.WorkListSolver
  # complete
  - pascal.taie.Assignment
    # remove dispatch, all subclasses
  - pascal.taie.language.classes.ClassHierarchy
  - pascal.taie.language.classes.ClassHierarchyImpl
  - pascal.taie.analysis.graph.callgraph.CallGraphBuilder # remove PTABuilder
  - pascal.taie.analysis.graph.callgraph.CallGraphs # remove resolveCallee
  - pascal.taie.analysis.dataflow.analysis.ResultProcessor # handle empty call graph
testClasses:
  - pascal.taie.analysis.Tests
  - pascal.taie.analysis.graph.callgraph.cha.CHATest
  - pascal.taie.analysis.dataflow.analysis.constprop.InterCPTest
testResources:
  - cha/AbstractMethod.java
  - cha/VirtualCall.java
  - cha/StaticCall.java
  - cha/SpecialCall.java
  - cha/Recursion.java
  - cha/LongCallChain.java
  - cha/Interface.java
  - cha/Interface2.java
  - dataflow/constprop/inter/Example.java
  - dataflow/constprop/inter/ArgRet.java
  - dataflow/constprop/inter/Call.java
